---
title: Array Decomposition
author:
  - name: Jan de Leeuw
    orcid: 0000-0003-1420-1797
    email: jan@deleeuwpdx.net
    affiliation:
      - name: University of California Los Angeles
        city: Los Angeles
        state: CA
        url: www.ucla.edu
    license: "CC0"
date: last-modified
date-format: long
bibliography: [mypubs.bib, total.bib]
number-sections: true
pdf-engine: lualatex
keep-tex: true
format:
  pdf:
    fontsize: 12pt
    include-in-header:
      - preamble.tex
    keep-tex: true
    link-citations: true
    documentclass: scrartcl
    number-sections: true
  html:
    fontsize: 12pt
    include-in-header:
      - preamble.css
    keep-md: true
    number-sections: true
toc: true
toc-depth: 3
editor: source
papersize: letter
graphics: true
link-citations: true
mainfont: Times New Roman
abstract: TBD
---

```{r}
#| label: loadpackages
#| echo: false

suppressPackageStartupMessages(library(knitr, quietly = TRUE))
suppressPackageStartupMessages(library(tinytex, quietly = TRUE))
```

\sectionbreak 

**Note:** This is a working manuscript which will be expanded/updated
frequently. All suggestions for improvement are welcome. All qmd, tex, html,
pdf, R, and C files are in the public domain. Attribution will be appreciated,
but is not required. The files can be found at
<https://github.com/deleeuw/arrays>

\sectionbreak

# Introduction

# Decomposition

## Vectors

Suppose $\mathcal{L}$ is the space of real $n-$element vectors and $A$ is a positive definite matrix of order $n$. For all $x,y\in\mathcal{L}$ we define the inner product $\langle x, y\rangle:=x'Ay$ and for all $x\in\mathcal{L}$ we define the corresponding norm $\|x\|^2:=\sqrt{x'Ax}$. 

Suppose $\mathcal{M}$ is subspace of dimension $p$ and $X$ is an orthonormal basis for $\mathcal{M}$, i.e. $n\times p$ matrix with every column in $\mathcal{M}$ and
$X'AX=I$. If we want to find the closest point to $y\in\mathcal{L}$ in $\mathcal{M}$ we must minimize $\|y-X\beta\|^2$ over $\beta$. The unique minimum is attained at $\hat\beta=X'Ay$ and the projection of $y$ on $\mathcal{M}$ is $X\hat\beta=XX'Ay$.

The projector $P:=XX'A$ is a square matrix that is

* idempotent: $P^2=P$, and
* self-adjoint: for all $x,y\in\mathcal{L}$ $\langle x,Py\rangle=\langle Px, y\rangle$, i.e. $AP=P'A$.

We have $Px=x$ if and only if $x\in\mathcal{M}$. For any projector $P$ the matrix $I-P$ is also a projector, because

* $(I-P)^2=I-2P+P^2=I-P$, and
* $A(I-P)=A-AP=A-P'A=(I-P)'A$.

Moreover $P$ and $(I-P)$ are orthogonal, because $P(I-P)=P-P^2=0$.

Suppose $X_\perp$ is an $n\times(n-p)$ orthonormal basis of $\mathcal{M}_\perp$, the subspace of all $z$ such that $z'AX=0$. Thus
\begin{subequations}
\begin{equation}
\begin{bmatrix}X'\\ X_\perp'\end{bmatrix}A\begin{bmatrix}X&X_\perp\end{bmatrix}=\begin{bmatrix}I&0\\0&I\end{bmatrix},
\end{equation}
and consequently
\begin{equation}
\begin{bmatrix}X&X_\perp\end{bmatrix}\begin{bmatrix}X'\\ X_\perp'\end{bmatrix}=A^{-1}.
\end{equation}
\end{subequations}
It follows that $X_\perp X_\perp'A=I-XX'A=I-P$. Thus $I-P$ projects on $\mathcal{M}_\perp$.
We have
\begin{align}
\|Px\|^2&=x'P'APx=x'AP^2x=x'APx=\langle x, Px\rangle,\\
\|(I-P)x\|^2&=x'(I-P')A(I-P)x=x'Ax-x'APx=\|x\|^2-\|Px\|^2,\\
\langle Px, (I-P)y\rangle&=x'P'A(I-P)y=x'P'Ay-x'P'APy=0.
\end{align}
It is trivially true for any square $P$ that $x=Px+(I-P)x$, but
$Px$ and $(I-P)x$ are orthogonal if and only if $P$ is a 
projector, and in that case we also have Pythagoras
\begin{equation}
\|x\|^2=\|Px\|^2+\|(I-P)x\|^2.
\end{equation}

We can generalize the decomposition $x=Px+(I-P)x$ to several mutually orthogonal
subspaces $\mathcal{M}_1,\cdots,\mathcal{M}_m$, with corresponding projectors 
$P_1,\cdots,P_m$. If
$P_1+\cdots+P_m=I$ we can have the decomposition in orthogonal parts
\begin{equation}
x=P_1x+P_2x+\cdots P_mx,
\end{equation}
and if $P_1+\cdots+P_m\lesssim I$ in the Loewner
sense\footnote{The eigenvalues of $P_1+\cdots+P_m$ are less than or equal to one.}
then
\begin{equation}
x=P_1x+P_2x+\cdots P_mx+(I-P_1-\cdots-P_m)x
\end{equation}
Note that the "residual" $I-P_1-\cdots-P_m$ is orthogonal to all
$P_1,\cdots,P_m$.

Suppose $U$ is an $n\times n$ matrix with $U'U=nI$ and with first column equal
to $e$. Define $\alpha:=n^{-1}U'x$ and $P_j:=n^{-1}u_ju_j'$. The $P_j$ are
projectors orthogonal to each other. Then
\begin{equation}
U\alpha=\sum_{j=1}^nP_jx=(\frac{1}{n}ee')x+(I-\frac{1}{n}ee')x=x_\bullet e+(x-x_\bullet).
\end{equation}
Although $\alpha$ depends on the choice of $U$ the product $U\alpha$ is the same
for all $U$.

We can also derive the decomposition from a least squares projection
perspective. Suppose we want to minimize $\|x-a\|^2$ over all $a$ of the form
$a=\alpha e$. The solution for $\alpha$ is, of course, $Px=x_\bullet$. And we
may want to minimize $\|x-a\|^2$ over all $a$ satisfying $e'a=0$, which gives
the solution $(I-P)x=x-x_\bullet$.

The projection formulation suggests some obvious further generalizations. We can
replace the one-dimensional subspace of all constant vectors by an arbitrary
subspace $S$, and we can replace the inner product $x'y$ by an arbitrary inner
product $x'Ay$, with $A$ positive semi-definite. If $H$ is an $A$-orthonormal
basis for the subspace $S$, i.e. if $H'AH=I$, then $Px=HH'Ax$ or $(x-Px)'Az=0$
for all $z\in S$.

In the next sections we analyse the same approaches we have used for vectors to
decompositions of linear spaces of matrices and arrays. This is actually not as
much of a generalization as it appears to be, because matrices and arrays are
elements of inner product spaces, just like vectors are. What we will introduce
are different notations and in most cases different inner products.

## Matrices

Suppose $X$ is an $n\times m$ matrix, an element of the space
$\mathbb{R}^{n\times m}$ with inner product $\langle X,Y\rangle:=\text{tr}\ X'Y$
and squared norm $\|X\|^2=\text{tr}\ X'X$. The elementwise decomposition we are
interested in is
\begin{equation}
x_{ij}=x_{\bullet\bullet}+(x_{i\bullet}-x_{\bullet\bullet})+(x_{\bullet j}-x_{\bullet\bullet})+
(x_{ij}-x_{i\bullet}-x_{\bullet j}+x_{\bullet\bullet}).\label{eq-twodimelem}
\end{equation}
Using ANOVA terminology we have the *overall effect*, the two *main effects* for
rows and columns, and the *first order interaction* of the rows and columns.

In the language of projectors we define
\begin{subequations}
\begin{align}
P_r&:=n^{-1}ee',\\
P_c&:=m^{-1}ee',
\end{align}
\end{subequations}
and with $Q_r:=I-P_r$ and $Q_c:=I-P_c$. Equation \eqref{eq-twodimelem} becomes
\begin{equation}
X=P_rXP_c+P_rXQ_c+Q_rXP_c+Q_rXQ_c.\label{eq-twodimproj}
\end{equation}
Thus again we have four projectors, orthogonal to each other, adding up to the
identity.

In @deleeuw_E_26e we generalize the results in this section to the inner product
$\langle X,Y\rangle:=\text{tr}\ RXCY'$, with $R$ and $C$ positive semi-definite.
Decomposition \eqref{eq-twodimproj} remains correct, with $P_r=ee'R/e'Re$ and
$P_c=Cee'/e'Ce$. Note that both projectors are asymmetric. Equation
\eqref{eq-twodimelem} also remains valid, if we interpret the bullitt subscripts
as weighted means.

To see more clearly how the vector case and the matrix case are different we use
the vec() operator to map $\mathbb{R}^{n\times m}$ into $\mathbb{R}^{nm}$. Using
the Kronecker product $\otimes$ of matrices we have the identity
\begin{equation}
\text{tr}\ RXCY'=x'(C\otimes R)y,
\end{equation}
with $x:=\text{vec}(X)$ and $y=\text{vec}(Y)$. Thus our matrix results can be
interpreted as a special case of the vector results in $\mathbb{R}^{nm}$, with
inner product $x'(C\otimes R)y$.

Now we switch to using orthogonal functions on a product space. This part is
inspired by an anonymous and unpublished manuscript that I read around 1980 with
a title that might have been "Lois de Probabilité sur un Ensemble Produit" and
perhaps the words "Décomposition" and/or "Interaction" were also in the title or
subtitle. It was either by Jean-Paul Benzécri or by one of his students or
co-workers. I did have a copy and I lost it, and Google can't find me a new one.
The published paper by @bener_82 discusses the same materials, but in less
detail.

Define $U$ and $V$ to be square matrices with first column equal to $e$,
$U'U=nI$ and $V'V=mI$. Note this implies $UU'=nI$ and $VV'=mI$, and thus
$UU'-ee'=nJ_n$ and $VV'-ee'=mJ_m$. Define $\alpha_{ij}:=(nm)^{-1}u_i'Xv_j$. Then
\begin{equation}
a_{ij}u_iv_j'=P_i^UXP^V_j,
\end{equation}
where $P_i^U:=n^{-1}u_iu_i'$ and $P_j^V:=\frac{1}{m}v_jv_j'$ project on the
lines through the origin and respectively $u$ and $v$. Using these projectors we
have the identity
\begin{equation}
X=\sum_{i=1}^n\sum_{j=1}^m\alpha_{ij}u_iv_j'=\sum_{i=1}^n\sum_{j=1}^mP_i^UXP^V_j,
\end{equation}
and $\|X\|^2=\|A\|^2$, where $A:=\{\alpha_{ij}\}$. If $i\neq k$ then
$P_i^UP_k^U=0$ and if $j\neq l$ then $P_j^VP_l^V=0$. Moreover if $I$ and $K$ are
disjoint subsets of $\{1,\cdots,n\}$ then
\begin{equation}
\left(\sum_{i\in I}P_i^U\right)\left(\sum_{k\in K}P_k^U\right)=0.
\end{equation}
Although $P_i^U$ and $P_j^V$ are projectors on $\mathbb{R}^n$ and
$\mathbb{R}^m$, they are only the building blocks for the projectors on
$\mathbb{R}^{n\times m}$ that we use in this section. Define
\begin{equation}
\Pi_{ij}(X):=P_i^UXP_j^V
\end{equation}
then $\Pi_{ij}$ projects $\mathbb{R}^{n\times m}$ on the line through the origin
and $u_iv_j'$. Thus $\Pi_{ij}\circ\Pi_{ij}=\Pi_{ij}$ and
$\Pi_{ij}\circ\Pi_{kl}= 0$ unless $i=k$ and $j=l$. Also
\begin{equation}
\|X\|^2=\sum_{i=1}^n\sum_{j=1}^m\|\Pi_{ij}(X)\|^2
\end{equation}

\begin{subequations}
\begin{align}
\Pi_{11}(X)&=x_{\bullet\bullet}ee'.\\
\sum_{j\neq 1}^m\Pi_{1j}(X)&=e(x_{\bullet_j}-x_{\bullet\bullet})',\\
\sum_{i\neq 1}^m\Pi_{i1}(X)&=(x_{i\bullet}-x_{\bullet\bullet})e',\\
\sum_{i\neq 1}^n\sum_{j\neq 1}^m\Pi_{ij}(X)=J_nXJ_m&=(x_{ij}-x_{i\bullet}e'-ex_{j\bullet}'+x_{\bullet\bullet})
\end{align}
\end{subequations}

Although the $\Pi_{ij}$ depend on the choice of $U$ and $V$ the partial sums
defining the main effects and the interaction are independent of $U$ and $V$.

## Arrays

If $X$ is an $n\times m\times\ell$ array then the basic elementwise
decomposition we are interested in is
\begin{align}
x_{ijk}&=x_{\bullet\bullet\bullet}+(x_{i\bullet\bullet}-x_{\bullet\bullet\bullet})+(x_{\bullet j \bullet}-x_{\bullet\bullet\bullet})+(x_{\bullet\bullet k}-x_{\bullet\bullet\bullet})\\
&+(x_{ij\bullet}-x_{i\bullet\bullet}-x_{\bullet j\bullet}+x_{\bullet\bullet\bullet})\\
&+(x_{i\bullet k}-x_{i\bullet\bullet}-x_{\bullet\bullet k}+x_{\bullet\bullet\bullet})\\
&+(x_{\bullet jk}-x_{\bullet j\bullet}-x_{\bullet\bullet k}+x_{\bullet\bullet\bullet})\\
&+(x_{ijk}
-x_{ij\bullet}-x_{i\bullet k}-x_{\bullet jk}+x_{i\bullet\bullet}+x_{\bullet j\bullet}+x_{\bullet\bullet k}-x_{\bullet\bullet\bullet})
\end{align}

\sectionbreak

# Correspondence Analysis

Suppose $F$ is a two-dimensional $n\times m$ contingency table, normalized to
have grand total equal to one, with row marginals in a diagonal matrix $D$ and
column marginals in a diagonal matrix $E$. Use the inner product
$\langle F,G\rangle=\text{tr}\ D^{-1}FE^{-1}G'$. The projectors are
$$
f_{ij}/d_ie_j=1+\sum_{s=1}^m u_{is}v_{js}
$$

# Log-linear Analysis

# References
